"""
Migrations for the api app are not used in live code as all its models are not
managed by Django. But during tests, Django automatically creates and destroyes
test dbs and in order to do that we need migrations.
Migrations were generated with:
$ manage.py makemigrations api
Migrations are in this unusual path as they belong only to tests. The path is
set in settings.MIGRATION_MODULES.
"""
# Generated by Django 2.1.4 on 2018-12-04 11:56
import sys

from django.db import migrations, models


MANAGED = True
# Set managed to False when running `makemigrations` to trick it otherwise
# it will generated a new migration to match the models (which have managed=False).
if 'makemigrations' in sys.argv or 'migrate' in sys.argv:
    MANAGED = False


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyRecordsMirror',
            fields=[
                ('recid', models.IntegerField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField()),
                ('marcxml', models.BinaryField()),
                ('valid', models.BooleanField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('collection', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'legacy_records_mirror',
                'managed': MANAGED,
            },
        ),
    ]
